CHANNELS = {
    "KTV이매진": "UCj8Snyrs1y-wnBQiUmGrTjw",
    "NATV_korea": "UCsWa6xl7KxOolVhROUJ4Ghw",
    "이재명tv": "UCNJM6dqu70Qr6VaseiW1Org",
    "dailyminjoo": "UCoQD2xsqwzJA93PTIYERokg",
    "KTV_korea": "UCIMOytYIzaUpoAM2bpT4JZQ",
    "MBCNEWS11": "UCF4Wxdo3inmxP-Y59wXDsFw",
    "Jtvnews2021": "UCWGk_-J9WJxgFBAgJXi4ilA",
    "g1tvnews": "UCx7D8prcWx7m8qy2xEiT7pA",
    "mbcradio_sisa": "UCTTmtS2ljy1vyl_s-d_LEHQ",
    "maebulshow": "UCMYhq9OyGI5UEz_NTAoHY7A",
    "gyeomsonisnothing": "UCAAvO0ehWox1bbym3rXKBZw",
    "취재편의점": "UCAVVxLmPDFkSTROPue8ZrRA",
    "SPEAKS_TV": "UCgeOlLcX6PReHdWImEnUVTg",
    "daeannews": "UClgTJWXTyDDBVWr0g5LjR8w",
    "HankyorehTV": "UCw7ZbT9Js4Vru6HSEk1NHyw",
    "sisaineditor": "UCaVuYo_tiiNzTSmlnM-A2kQ",
    "choikytv": "UCE-94tymU-LjuglJ_wqzhHA",
    "사장남천동": "UCUFpe4kv7GRPEddLfCJOIzQ",
    "kangsungbumTV": "UCMNGwNS4yCEsCCyu2soQDrQ",
    "여의도옆문래동": "UC3cxhquPL-anKgzqj0ndzoA",
    "백운기의정어리TV": "UCnj0yVadEmXKcUN5ztUY4uw",
    "봉지욱기자": "UC9mEeE55q4PCfGERt_PNYbg",
    "DHLeeTV": "UC3TdlUq20joza2kS0Nl0sSw",
}
